name: SpeedrunRace
version: 1.0.1
main: xyz.pyxismc.speedrunrace.SpeedrunRace
api-version: 1.21.11
depend: [LuckPerms, Chunky]

commands:
  race:
    description: Admin commands for managing the race.
    usage: /race <pregen|start>
    permission: race.admin
    permission-message: §cYou don't have permission to use this command.
  join:
    description: Allow the player to join a team.
    usage: /join <nom_equipe>

permissions:
  race.admin:
    description: administrator permissions for managing.
    default: op